apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mechanicbuddy-system-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mechanicbuddy

  source:
    repoURL: https://github.com/D4m13n-D3v/mechanicbuddy.git
    targetRevision: main
    path: infrastructure/k8s/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: mechanicbuddy-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health checks
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ''
      kind: Secret
      jsonPointers:
        - /data

  info:
    - name: Environment
      value: staging
    - name: Team
      value: platform
