{{/*
Expand the name of the chart.
*/}}
{{- define "mechanicbuddy-free-tier.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "mechanicbuddy-free-tier.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "mechanicbuddy-free-tier" }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "mechanicbuddy-free-tier.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "mechanicbuddy-free-tier.labels" -}}
helm.sh/chart: {{ include "mechanicbuddy-free-tier.chart" . }}
{{ include "mechanicbuddy-free-tier.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
mechanicbuddy.app/instance-type: free-tier
{{- end }}

{{/*
Selector labels
*/}}
{{- define "mechanicbuddy-free-tier.selectorLabels" -}}
app.kubernetes.io/name: {{ include "mechanicbuddy-free-tier.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
API selector labels
*/}}
{{- define "mechanicbuddy-free-tier.api.selectorLabels" -}}
app.kubernetes.io/name: {{ include "mechanicbuddy-free-tier.name" . }}-api
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/component: api
{{- end }}

{{/*
Web selector labels
*/}}
{{- define "mechanicbuddy-free-tier.web.selectorLabels" -}}
app.kubernetes.io/name: {{ include "mechanicbuddy-free-tier.name" . }}-web
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/component: web
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "mechanicbuddy-free-tier.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "mechanicbuddy-free-tier.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
PostgreSQL cluster name
*/}}
{{- define "mechanicbuddy-free-tier.postgresName" -}}
{{- printf "%s-postgres" (include "mechanicbuddy-free-tier.fullname" .) }}
{{- end }}

{{/*
Secret name for database credentials (auto-generated by CloudNativePG)
*/}}
{{- define "mechanicbuddy-free-tier.dbSecretName" -}}
{{- printf "%s-postgres-app" (include "mechanicbuddy-free-tier.fullname" .) }}
{{- end }}

{{/*
Secret name for JWT and app secrets
*/}}
{{- define "mechanicbuddy-free-tier.appSecretName" -}}
{{- printf "%s-app-secrets" (include "mechanicbuddy-free-tier.fullname" .) }}
{{- end }}

{{/*
Namespace for the free-tier instance
*/}}
{{- define "mechanicbuddy-free-tier.namespace" -}}
{{- .Values.instance.namespace }}
{{- end }}
